import turtle

turtle.bgcolor('silver')
turtle.setup(width=900, height=900)
turtle.title("Avengers Logo")
turtle.speed(5)
turtle.pensize(10)

turtle.penup()

#drawing black circle around the A symbol
def draw_Circle():
    turtle.setposition(0,-300)
    turtle.pendown()
    turtle.pencolor('black')
    turtle.color('black')
    turtle.begin_fill()    
    turtle.circle(300)
    turtle.end_fill()
    turtle.penup()

    turtle.setposition(0,-250)
    turtle.pendown()
    turtle.pencolor('silver')
    turtle.color('silver')
    turtle.begin_fill()    
    turtle.circle(250)
    turtle.end_fill()
    turtle.penup()

#drawing the A symbol
def draw_Symbol():
    turtle.setposition(80,-160)
    turtle.pendown()
    turtle.color('black')
    turtle.pencolor('black') 
    turtle.begin_fill() 
    turtle.forward(95)
    turtle.right(-95)
    turtle.forward(520)
    turtle.right(95)
    turtle.backward(100)
    turtle.right(110)
    turtle.forward(700)
    turtle.right(-110)
    turtle.forward(85)
    turtle.right(110)
    turtle.forward(-220)
    turtle.right(-110)
    turtle.forward(130)
    turtle.right(90)
    turtle.forward(67)
    turtle.end_fill()
    turtle.penup()

    turtle.setposition(-10,0)
    turtle.pendown()
    turtle.color('silver')
    turtle.pencolor('silver')
    turtle.begin_fill() 
    turtle.right(20)
    turtle.forward(-240)
    turtle.right(160)
    turtle.forward(-230)
    turtle.right(90)
    turtle.forward(-84)
    turtle.end_fill()
    turtle.penup()
       
#drawing spacing between circle and A symbol
def draw_Spacing():
    turtle.setposition(-165,-150)
    turtle.pendown()
    turtle.pencolor('silver')
    turtle.right(110)
    turtle.forward(170)
    turtle.right(-110)
    turtle.forward(105)
    turtle.right(-70)
    turtle.forward(105)
    turtle.penup()

    turtle.setposition(70,60)
    turtle.pendown()
    turtle.pencolor('silver')
    turtle.right(120)
    turtle.forward(155)
    turtle.right(80)
    turtle.forward(155)
    
draw_Circle()
draw_Symbol()
draw_Spacing()

turtle.done()